language: java
sudo: false

matrix:
  include:
    - os: linux
      jdk: openjdk11
    - os: osx
      osx_image: xcode10.2

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install ant; fi

script:
  - ant -f make-jar.xml
