language: java
sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

addons:
  apt:
    packages:
      - oracle-java8-installer

script: ant -f make-jar.xml
