language: java
sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode10.1

addons:
  apt:
    packages:
      - oracle-java8-installer

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install ant; fi

script:
  - ant -f make-jar.xml
